### ISSUE TITLE
Error when using the addon

### ISSUE THREAD

**Issue by Slevi2009** [Olyno/skent#47]
## Describe your problem

Error when trying to copy folder

## Versions

**Skript:** 2.8.4
**Server:** Current: git-Purpur-2062 (MC: 1.20.1)*
**Skent:** 3.2.2

## Code

```vb
command /save:
	trigger:
		copy file path "/world/" to file path "/savedworlds/"
```

## Error

https://pastebin.com/4TN4n6R0

**Comment by Olyno** [comment]
Hi 👋🏻 

Thank you for the report. It should show you a FileNotFound error instead of a IO exception. That being said, you have this error because your directory ``/world/`` does not exist.

Remember, when using a ``/`` at the start of the path, it mean "root" in Linux, which **is not** your server root. You can see what the "real" file path looks like by using ``absolute path of file path "/world/"``. 

By default, your paths are already in the server root, so removing your ``/`` at the beginning of your path *should* fix this issue.

 Please reopen this issue if it is not fixed.
