### ISSUE TITLE
The variables within the functions do not work when creating a file.

### ISSUE THREAD

**Issue by Blacksoul16** [Olyno/skent#9]
## Describe your problem
When I create a file using a variable, in this case {_p} (the player himself), instead of creating "Blahblahblah.yml" (this is an example), what is created is "< none >.yml". All this process is within functions.

## Versions

**Skript:** 2.5.3
**Server:** git-Paper-323 (MC: 1.16.4)
**Skent:** 2.1.0

## Code

```vb
options:
   prefix: <##00E4FF>&lSurvival &7>>

function crearDatosUsuario(p: player):
   create file path "plugins/Fraternity Survival/User caché/%{_p}%.yml"
   #establecer estadísticas luego.
   send "{@prefix} &aTus datos se crearon con éxito." to {_p}

function verificarDatosUsuario(p: player):
   if file path "plugins/Fraternity Survival/User caché/%{_p}%.yml" is missing:
      send "{@prefix} &eCreando tus datos..." to {_p}
      crearDatosUsuario({_p})

command /test:
   trigger:
      verificarDatosUsuario(player)
```

## Error
No errors in console.

**Comment by Olyno** [comment]
Hi, thanks for your report.
Unfortunately this problem is not directly related to Skent, but is related to Skript. Skript has a lot of problems with everything asynchronous and temporary variables, so only global variables work (if you try again by putting a global variable, the effect will work perfectly).
For the moment I can't do anything more, but I'll look for a solution.
